sudo: false

language: node_js

node_js:
  - 5

before_script:
  - npm run build
  - npm run lint

script:
  - npm run test:ci

notifications:
  email:
    recipients:
      - joshua.newman@krux.com
    on_success: [change]
    on_failure: [always]
