sudo: false

language: node_js

node_js:
  - 5

cache:
  directories:
    - node_modules

before_script:
  - npm prune

script:
- |
  npm run lint
  npm run build
  npm run test:ci
  if [ "${TRAVIS_PULL_REQUEST}" == "true" ]; then
    npm run test:cross-browser
  fi

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  email:
    recipients:
      - joshua.newman@krux.com
    on_success: [change]
    on_failure: [always]
